close #65 - Remove location model
lelylan/devices pull request #66
Opened 2017-02-06 17:37 UTC by FedeG

2017-03-12 10:29 UTC, andreareginato requested changes
When the refactoring in `application_controller` is done we can merge this.

2017-03-12 10:29 UTC, andreareginato commented on app/controllers/application_controller.rb
> +    @current_user ||= User.find(doorkeeper_token.resource_owner_id) if request.headers['Authorization'] or (not request.headers['X-Physical-Secret'] and doorkeeper_token)
I would try to clean it up a bit more. 
This way the `'X-Physical-Secret` token whenever it is set, will have priority

```
...
@current_user ||=  User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token or request.headers['Authorization']
@current_user ||= User.find(@device.resource_owner_id) if request.headers['X-Physical-Secret']
```

2017-03-14 21:26 UTC, FedeG commented on app/controllers/application_controller.rb
> +    @current_user ||= User.find(doorkeeper_token.resource_owner_id) if request.headers['Authorization'] or (not request.headers['X-Physical-Secret'] and doorkeeper_token)
-> https://github.com/lelylan/devices/pull/66/commits/e2d1db8ba04c531a055e9d5e2a8b80f584f43581

2017-03-19 16:54 UTC, merged

2017-03-19 16:54 UTC, andreareginato commented
Perfect work.